import requests
from datetime import datetime, timedelta

def get_location(ip):
    url = f"http://ip-api.com/json/{ip}"
    try:
        response = requests.get(url)
        data = response.json()
        if data.get("status") == "success":
            return f"{data['city']}, {data['country']}", data.get('isp', 'Unknown ISP')
        return "Private/Internal IP", "N/A"
    except:
        return "Connection Error", "N/A"

# --- CONFIGURATION ---
# Adjusting for your time (UTC + 1)
report_time = (datetime.now() + timedelta(hours=1)).strftime("%Y-%m-%d %H:%M:%S")
suspects = ["8.8.8.8", "1.1.1.1", "192.168.1.50", "104.21.19.201", "172.253.120.102"]

# --- GENERATING THE REPORT ---
with open("evidence_report.txt", "w") as f:
    f.write(f"OFFICIAL FORENSIC REPORT\n")
    f.write(f"Generated by: Investigator Razane\n")
    f.write(f"Timestamp: {report_time}\n")
    f.write("-" * 50 + "\n")
    f.write(f"{'IP ADDRESS':<15} | {'LOCATION':<25} | {'ISP'}\n")
    f.write("-" * 50 + "\n")

    for ip in suspects:
        location, isp = get_location(ip)
        f.write(f"{ip:<15} | {location:<25} | {isp}\n")

print("✅ Investigation Complete. Report saved to: evidence_report.txt")
